<?php

require_once dirname(__FILE__) . '/../../../../FieldDefinitions/TextFieldDefinition.php';

/**
 * Test class for TextFieldDefinition.
 * Generated by PHPUnit on 2011-05-30 at 22:48:23.
 */
class TextFieldDefinitionTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var TextFieldDefinition
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new TextFieldDefinition;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testManufacture().
	 */
	public function testManufacture() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetLength().
	 */
	public function testGetLength() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testMatchesSqlType().
	 */
	public function testMatchesSqlType() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testFromSQLCreateFieldLine().
	 */
	public function testFromSQLCreateFieldLine() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetLength().
	 */
	public function testSetLength() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetIsFixedWidth().
	 */
	public function testGetIsFixedWidth() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetIsFixedWidth().
	 */
	public function testSetIsFixedWidth() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsValidValue().
	 */
	public function testIsValidValue() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testRepairValue().
	 */
	public function testRepairValue() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testToSql().
	 */
	public function testToSql() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testExampleValue().
	 */
	public function testExampleValue() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}

?>
