<?php

require_once dirname(__FILE__) . '/../../../../IndexDefinitions/KeyDefinition.php';

/**
 * Test class for KeyDefinition.
 * Generated by PHPUnit on 2011-05-30 at 22:49:13.
 */
class KeyDefinitionTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var KeyDefinition
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testManufacture().
	 */
	public function testManufacture() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetIsKey().
	 */
	public function testSetIsKey() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}

?>
