<?php

require_once dirname(__FILE__) . '/../../../../FieldDefinitions/EmailFieldDefinition.php';

/**
 * Test class for EmailFieldDefinition.
 * Generated by PHPUnit on 2011-05-30 at 22:48:23.
 */
class EmailFieldDefinitionTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var EmailFieldDefinition
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new EmailFieldDefinition;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testSetAllowsLocalAddresses().
	 */
	public function testSetAllowsLocalAddresses() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAllowsLocalAddresses().
	 */
	public function testGetAllowsLocalAddresses() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsValidValue().
	 */
	public function testIsValidValue() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testRepairValue().
	 */
	public function testRepairValue() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}

?>
