<?php

require_once dirname(__FILE__) . '/../../../Deletable.php';

/**
 * Test class for Deletable.
 * Generated by PHPUnit on 2011-05-30 at 22:45:37.
 */
class DeletableTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Deletable
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testDelete().
	 */
	public function testDelete() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}

?>
