<?php

require_once dirname(__FILE__) . '/../../../../IndexDefinitions/PrimaryKeyDefinition.php';

/**
 * Test class for PrimaryKeyDefinition.
 * Generated by PHPUnit on 2011-05-30 at 22:49:13.
 */
class PrimaryKeyDefinitionTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var PrimaryKeyDefinition
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}
	
	public function testMatchesSqlType()
	{
		$expectTrue = array(
			"PRIMARY KEY (`UserID`, `AnotherColumn`)",
			"Primary key (`UserID`, `AnotherColumn`)",
			"Primary key `SomeTablePrimaryKey` (`UserID`, `AnotherColumn`)",
			"primary key (`UserID`)"
		);
		$expectFalse = array(
			"Primary Index (`UserID`)",
			"UNIQUE INDEX `SomeUniqueIndex` (`IndexField`)"
		);
		foreach ($expectTrue as $val)
		{
			$this->assertTrue(PrimaryKeyDefinition::matchesSqlType($val), $val);
		}
		foreach ($expectFalse as $val)
		{
			$this->assertFalse(PrimaryKeyDefinition::matchesSqlType($val));
		}
	}
	
	public function testFromSQLCreateIndexLine()
	{
		$line = "PRIMARY KEY (`TestField`, `TestField2`)";
		$x = PrimaryKeyDefinition::fromSQLCreateIndexLine($line);
		$this->assertEquals($line, $x->toSql());
	}

	/**
	 * @todo Implement testManufacture().
	 */
	public function testManufacture() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetIsPrimary().
	 */
	public function testSetIsPrimary() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}

?>
